# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hi',
                'doc_host': 'https://st01cs.github.io',
                'git_url': 'https://github.com/st01cs/nbdev-hi',
                'lib_path': 'nbdev_hi'},
  'syms': {'nbdev_hi.core': {'nbdev_hi.core.foo': ('core.html#foo', 'nbdev_hi/core.py')}}}
